{{- if and .Values.secrets.create (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edcadmin.fullname" . }}
  labels:
    {{- include "edcadmin.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth-password: {{ required "secrets.authPassword is required when secrets.create=true" .Values.secrets.authPassword | quote }}
  edc-api-key: {{ required "secrets.edcApiKey is required when secrets.create=true" .Values.secrets.edcApiKey | quote }}
  sts-client-secret: {{ .Values.secrets.stsClientSecret | default "" | quote }}
{{- end }}
